### ISSUE TITLE
修改条目标题之后，如果鼠标点击标题之外的区域，会导致修改丢失

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#1]
请看下列动图

![hulunote-issue01](https://user-images.githubusercontent.com/1609306/85426518-28668b00-b5ad-11ea-8eec-09e24d165b85.gif)

还有这个

![hulunote-issue19](https://user-images.githubusercontent.com/1609306/85928229-fa02eb80-b8dd-11ea-96e4-8fc5f4f03615.gif)

**Comment by chanshunli** [comment]
@pimgeek 改好啦，这个问题 :-D

**Comment by pimgeek** [comment]
我刚刚刷新了两次，还是会丢失全新输入的标题啊，无论是键盘上下按键离开，还是鼠标点别处移开。

**Comment by chanshunli** [comment]
@pimgeek , 我改好的是，修改了节点, 离开会消失的问题，标题的我看看哈, 马上改好 :-D

**Comment by chanshunli** [comment]
` 我刚刚刷新了两次，还是会丢失全新输入的标题啊，无论是键盘上下按键离开，还是鼠标点别处移开。 ` @pimgeek 已经改好了
