### ISSUE TITLE
选择文本块时，下面所有的文本块会往下移动

### ISSUE THREAD

**Issue by sahmoli** [hulunote/issues#11]
应该是和文本框的高度相关
![hulunote2](https://user-images.githubusercontent.com/3048515/85575388-18f94780-b66a-11ea-8be4-ff1e15e44903.gif)

**Comment by chanshunli** [comment]
这个最后再改,autosize编辑框框还没适配好 @sahmoli

**Comment by chanshunli** [comment]
@sahmoli 已经发布 :-D

![211122222211122211112](https://user-images.githubusercontent.com/6021537/85818068-48ab6b00-b7a2-11ea-96b5-704f968b1df4.gif)
