### ISSUE TITLE
葫芦笔记首页的标题和按钮，应写为“登录”，而不是“登陆”

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#12]
请看下面的截图

![image](https://user-images.githubusercontent.com/1609306/85690244-f6b50780-b705-11ea-9f2d-6bdeebe3e6d3.png)

**Comment by pimgeek** [comment]
还有登录成功之后的提示信息，也需调整

![image](https://user-images.githubusercontent.com/1609306/85690732-7216b900-b706-11ea-99fe-738c923854a6.png)

**Comment by chanshunli** [comment]
@pimgeek 改好了 :-D
