### ISSUE TITLE
刷新网页之后，原来显示的笔记条目消失，必须重新打开 app 首页才能找回

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#13]
请看下面的截图

![hulunote-issue13](https://user-images.githubusercontent.com/1609306/85809888-eb0c2400-b78b-11ea-8941-5d0b78dfd1f9.gif)

**Comment by chanshunli** [comment]
已经发布了: database页面, 笔记列表页面, 详情页面, 刷新后都能正常打开页面数据 :-D
