### ISSUE TITLE
图不能自动排布到页面中间

### ISSUE THREAD

**Issue by sahmoli** [hulunote/issues#19]
生成的图很大（见滚动条），但其实只有四个节点，需要拖动滚动条才能看到全图。
![image](https://user-images.githubusercontent.com/3048515/85934709-91d1fb00-b919-11ea-8c77-c67c78fddcf9.png)

**Comment by chanshunli** [comment]
@sahmoli ，我这边是正常显示能居中, 我远程一下你看看吧 :-D

**Comment by chanshunli** [comment]
@sahmoli 这个没问题了吧? :-D
