### ISSUE TITLE
编辑大纲标题的过程中，用上下方向键离开当前行时，编辑会丢失

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#23]
请看下面的截图

![hulunote-issue23](https://user-images.githubusercontent.com/1609306/86212036-eb505900-bba9-11ea-8244-8a8f4a5be6ef.gif)

这个问题与 #1 有关联，都是在编辑大纲标题时出现的问题

**Comment by chanshunli** [comment]
@pimgeek  已完成啦 :-D
