### ISSUE TITLE
收起侧边栏后留一个向左打开的小箭头

### ISSUE THREAD

**Issue by sahmoli** [hulunote/issues#27]
收起侧边栏后，可以在右边留一个向左打开的小箭头，就是红圈这个箭头翻转一下
![image](https://user-images.githubusercontent.com/3048515/86338352-d3013c80-bc84-11ea-8801-1ebf3a19a492.png)
现在的点击右上角三个点，然后再点击侧边栏不直观。
![image](https://user-images.githubusercontent.com/3048515/86338441-ead8c080-bc84-11ea-86b3-afd07e0cd06f.png)

**Comment by chanshunli** [comment]
@sahmoli 已完成啦 :-D
