### ISSUE TITLE
将笔记标题改为一个已有笔记的名字时候，没有经过用户同意自动合并

### ISSUE THREAD

**Issue by sahmoli** [hulunote/issues#29]
这样容易由于用户的误操作而造成错误。

**Comment by chanshunli** [comment]
![image](https://user-images.githubusercontent.com/6021537/86392392-f69ca500-bccd-11ea-8b55-d20437b1ebaf.png)


@sahmoli 改好啦 :-D

**Comment by sahmoli** [comment]
赞，可不可以把对话框调整到标题的旁边（上面那个红框的位置），这样用户的鼠标只需要挪动最短距离就可以点击了。
![image](https://user-images.githubusercontent.com/3048515/86421215-bc51f880-bd0b-11ea-90f0-e98b9a590f57.png)

这是Roam的效果，一个极简的提示框，只有一行，可以最大程度地减少侵害用户的注意力。
![image](https://user-images.githubusercontent.com/3048515/86421258-edcac400-bd0b-11ea-9e2e-858ebee679bc.png)

**Comment by chanshunli** [comment]
@sahmoli 优秀 👍 💯 可以呀 :-D 已经发布了
