### ISSUE TITLE
在[[]]中打字，用鼠标选中某推荐结果之后，[[]]里面的内容并没有发生相应的变化

### ISSUE THREAD

**Issue by sahmoli** [hulunote/issues#31]
![image](https://user-images.githubusercontent.com/3048515/86339309-02647900-bc86-11ea-9776-1f64d48cda66.png)
点击卢曼笔记之后，这个文本框还是[[卢曼]]

**Comment by chanshunli** [comment]
@sahmoli 已经解决啦 :-D
