### ISSUE TITLE
点击页面别的地方后，搜索结果框不会自动收起来

### ISSUE THREAD

**Issue by sahmoli** [hulunote/issues#35]
![image](https://user-images.githubusercontent.com/3048515/86428153-aac61c00-bd1e-11ea-9c4f-3856806e6bb8.png)

**Comment by sahmoli** [comment]
现在如果搜索框有内容的话，点击页面别的地方，搜索框还是会一直停在那儿

**Comment by chanshunli** [comment]
@sahmoli  已完成 :-D
