### ISSUE TITLE
希望通过快捷键调整大纲笔记的上下顺序（WorkFlowy 支持这种操作）

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#4]
请看下面的动图

![hulunote-issue04](https://user-images.githubusercontent.com/1609306/85478250-7a7bd080-b5ee-11ea-899f-7e6edcc414d9.gif)

WorkFlowy 的操作快捷键：

* `Alt+Shift+ 上/下`：调整笔记条目的上下位置
* `Alt+Shift+ 左/右`：调整笔记条目的缩进级别

**Comment by chanshunli** [comment]
Roam 的上下移动block的快捷键是: 

Move Block Up : `Cmd-Shift-Up`
Move Block Down: `Cmd-Shift-Down`

Windows 用 `Alt+Shift+ 上/下`  还是 ` Ctrl+Shift+ 上/下 ` ?

**Comment by pimgeek** [comment]
> Windows 用 `Alt+Shift+ 上/下` 还是 `Ctrl+Shift+ 上/下` ?

只要实现操作指令，可以绑定快捷键即可

**Comment by chanshunli** [comment]
已经发布了 @pimgeek :-D

**Comment by pimgeek** [comment]
我这里还没生效哦 。。。

![hulunote-issue04-a](https://user-images.githubusercontent.com/1609306/85737338-e155d280-b731-11ea-9706-843ca8918743.gif)

**Comment by chanshunli** [comment]
@pimgeek 这个按钮忘了加了，你按`Alt+Shift+ 上/下`是可以的.

**Comment by chanshunli** [comment]
@pimgeek  发布了 ,下面的按钮也支持了 :-D

**Comment by pimgeek** [comment]
还是有些问题，我在反复实验中，这是其中一种表现……

![hulunote-issue04-b](https://user-images.githubusercontent.com/1609306/85809558-f27efd80-b78a-11ea-9324-45bda44e4905.gif)

**Comment by chanshunli** [comment]
@pimgeek 🤣 , 这一小排按钮和编辑框的之间的离开事件要绑定一下, 我改改:-D

**Comment by chanshunli** [comment]
@pimgeek 改好了，小按钮上下可以排序使用了

**Comment by pimgeek** [comment]
这次确实三角按键正常了，就差键盘快捷方式了 👍
