### ISSUE TITLE
如何删除笔记？点击所有笔记右面的三个点直接进入笔记，没有其他选项

### ISSUE THREAD

**Issue by sahmoli** [hulunote/issues#43]
![image](https://user-images.githubusercontent.com/3048515/86432526-a3a50b00-bd2a-11ea-9cb2-c6930ac71eb2.png)

这是Roam的所有笔记页面作为参考，使用多选框来实现的。且以列表方式呈现更多信息，也方便快速排序
![image](https://user-images.githubusercontent.com/3048515/86432524-97b94900-bd2a-11ea-95d0-56826ac21c14.png)

**Comment by chanshunli** [comment]
@sahmoli 有两个删除入口, 一个是首页,另外一个是主编辑页, 主编辑页删除可以了 :-D 

<img width="1016" alt="截屏2020-07-05 下午8 50 55" src="https://user-images.githubusercontent.com/6021537/86533125-6c3c8700-bf01-11ea-8d43-5f3b11cec56c.png">

**Comment by sahmoli** [comment]
赞，最好在点击删除之后加上一个确认的过程吧，放置误删

**Comment by chanshunli** [comment]
@sahmoli 可以的 :-D

**Comment by chanshunli** [comment]
@sahmoli 终于改好了首页的批量选中删除 , 还有询问是否删除, 还有主编辑页面的删除也有询问 :-D
