### ISSUE TITLE
光标所在行的高亮背景遮挡了笔记工具的提示信息

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#47]
请看下面的截图

![image](https://user-images.githubusercontent.com/1609306/86504938-7bccaa80-bdf1-11ea-9d45-17a41bb34a17.png)

**Comment by chanshunli** [comment]
<img width="699" alt="截屏2020-07-04 下午1 23 53" src="https://user-images.githubusercontent.com/6021537/86505616-a6bafc80-bdf9-11ea-9e38-47a2544b5dd2.png">

@pimgeek 已经修改好啦 :-D 悬浮在最顶层
