### ISSUE TITLE
希望通过快捷键调整复杂大纲的折叠/展开（WorkFlowy 支持这个）

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#5]
请看下面的动图

![hulunote-issue05](https://user-images.githubusercontent.com/1609306/85478814-8320d680-b5ef-11ea-9d4c-e797a08b3596.gif)

**Comment by chanshunli** [comment]
Mac 上的`Ctrl-Up/Down`被系统占用了, 要改成`Meta-Up/Down` @pimgeek

**Comment by pimgeek** [comment]
> Mac 上的`Ctrl-Up/Down`被系统占用了, 要改成`Meta-Up/Down` @pimgeek

可以，参考 Dynalist 的处理方法就行，Dynalist Pro 用户可以自定制键盘快捷键
（Windows / Mac 的默认快捷键不同是正常的，只要有这样一个操作可以被绑定快捷键即可）

**Comment by chanshunli** [comment]
Meta-Up/Down 已经支持了, windows是alt +  Meta-Up/Down 。
后面可以做一个自定义键盘的功能. @pimgeek

**Comment by pimgeek** [comment]
> Meta-Up/Down 已经支持了, windows是alt + Meta-Up/Down 。
> 后面可以做一个自定义键盘的功能. @pimgeek

Windows 上的折叠 / 展开快捷键貌似是 Ctrl + Up / Down？😅

**Comment by chanshunli** [comment]
@pimgeek  👍 😆
