### ISSUE TITLE
希望光标所在的大纲条目可以背景色高亮（参考 Dynalist iOS App）

### ISSUE THREAD

**Issue by pimgeek** [hulunote/issues#8]
编辑时更容易区分

![image](https://user-images.githubusercontent.com/1609306/85483167-ea8e5480-b5f6-11ea-874b-0d0b6c2d04d9.jpeg)

**Comment by chanshunli** [comment]
@pimgeek 已经发布了 :-D
![211122222211122211112](https://user-images.githubusercontent.com/6021537/85818127-709ace80-b7a2-11ea-9e3d-9fb0a497330e.gif)

**Comment by pimgeek** [comment]
CentBrowser 中已经 OK 了，但是 Edge 浏览器内好像还没生效 

![hulunote-issue08a](https://user-images.githubusercontent.com/1609306/85842129-c5a20900-b7d1-11ea-8cce-fc94988d4066.gif)

**Comment by chanshunli** [comment]
换了一个颜色比较深的 :-D @pimgeek 
![image](https://user-images.githubusercontent.com/6021537/86186606-1a47da00-bb6c-11ea-9940-234d850d10ca.png)
